# Data Cleaning Practice - Questions

## 🎯 Objective
Clean a messy customer sales dataset that contains various data quality issues including:
- Missing values
- Duplicate records
- Inconsistent formatting
- Invalid data
- Outliers
- Data type issues

**Dataset:** customer_sales_data.csv

**Total Questions:** 30 (Progressive difficulty)

## Setup

In [2]:
import pandas as pd
import numpy as np
# import matplotlib.pyplot as plt
# import seaborn as sns
# import re
from datetime import datetime

# Display settings
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', 100)

# Load data
df = pd.read_csv('csv data files/customer_sales.csv')
print(f"Dataset loaded! Shape: {df.shape}")
df.head()

Dataset loaded! Shape: (52, 17)

,customer_id,customer_name,email,phone,age,gender,city,country,registration_date,product_category,purchase_amount,quantity,discount,payment_method,shipping_status,customer_rating,last_purchase_date
0,C001,John Smith,john.smith@email.com,555-1234,28.0,Male,New York,USA,2023-01-15,Electronics,1200.50,2,10.0,Credit Card,Delivered,4.5,2024-11-20
1,C002,MARIA GARCIA,maria@email.com,555-2345,34.0,Female,Los Angeles,usa,01/20/2023,Clothing,450.75,5,15.0,PayPal,Shipped,5.0,2024-11-18
2,C003,james wilson,jameswilson@email,555-3456,-5.0,Male,Chicago,NaN,2023-02-10,Electronics,2500.00,1,20.0,Credit Card,Delivered,4.8,2024-11-15
3,C004,Lisa Anderson,lisa.anderson@email.com,NaN,29.0,F,Houston,USA,2023-03-05,Home & Garden,780.25,3,10.0,Debit Card,Delivered,NaN,2024-11-22
4,C005,Robert Brown,robert.brown@email.com,555-5678,42.0,Male,Phoenix,USA,2023-04-12,Electronics,NaN,2,5.0,Credit Card,Shipped,4.2,2024-11-19

#### data cleaning

In [3]:
df.sample()

,customer_id,customer_name,email,phone,age,gender,city,country,registration_date,product_category,purchase_amount,quantity,discount,payment_method,shipping_status,customer_rating,last_purchase_date
35,C034,Timothy Wright,timothy@invalid,555-2348,36.0,M,Mesa,USA,2023-09-10,Clothing,NaN,5,15.0,Debit Card,Shipped,4.4,2024-10-25

In [4]:
df["customer_name"].isnull()

0     False
1     False
2     False
3     False
4     False
5      True
6     False
7     False
8     False
9     False
10    False
11    False
12    False
13    False
14    False
15    False
16    False
17    False
18    False
19    False
20    False
21    False
22    False
23    False
24     True
25    False
26    False
27    False
28    False
29    False
30    False
31    False
32    False
33    False
34    False
35    False
36    False
37    False
38    False
39    False
40    False
41    False
42    False
43    False
44    False
45    False
46    False
47    False
48    False
49    False
50    False
51    False
Name: customer_name, dtype: bool

##### cleaning customer name

In [5]:
def clean_name(x):
    if pd.isna(x):
        return x
    return str(x).title()

In [6]:
df["customer_name"].apply(clean_name)

0              John Smith
1            Maria Garcia
2            James Wilson
3           Lisa Anderson
4            Robert Brown
5                     NaN
6             Emily Davis
7            Maria Garcia
8            Michael  Lee
9            Sarah Taylor
10         David Martinez
11         Jennifer White
12    Christopher Johnson
13        Amanda Thompson
14          Daniel Garcia
15       Jessica Martinez
16          Matthew Brown
17          Ashley Wilson
18           Joshua Davis
19      Michelle Anderson
20          Andrew Thomas
21        Stephanie Moore
22        Brandon Jackson
23          Nicole Martin
24                    NaN
25          Rachel Harris
26           Justin Clark
27          Melissa Lewis
28          Ryan Robinson
29           Laura Walker
30             Brian Hall
31         Jennifer White
32         Kimberly Allen
33            Jason Young
34             Donna King
35         Timothy Wright
36           Sharon Lopez
37           Kenneth Hill
38          Deborah Scott
39           George Green
40         Patricia Adams
41           Edward Baker
42        Sandra Gonzalez
43          Donald Nelson
44           Carol Carter
45        Steven Mitchell
46             Ruth Perez
47           Joseph Moore
48           Nancy Taylor
49         Kevin Anderson
50            Betty White
51          Gary Martinez
Name: customer_name, dtype: object

---
## Part 1: Initial Data Exploration (Q1-5)
---

### Question 1: Basic Data Overview
**Task:**
- Display the shape of the dataset
- Show all column names and their data types
- Display the first 10 rows
- Show basic statistics for numeric columns

In [7]:
# Your code here
df.shape
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 52 entries, 0 to 51
Data columns (total 17 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   customer_id         52 non-null     object
 1   customer_name       50 non-null     object
 2   email               52 non-null     object
 3   phone               45 non-null     object
 4   age                 47 non-null     float64
 5   gender              52 non-null     object
 6   city                50 non-null     object
 7   country             51 non-null     object
 8   registration_date   50 non-null     object
 9   product_category    52 non-null     object
 10  purchase_amount     43 non-null     float64
 11  quantity            52 non-null     int64
 12  discount            51 non-null     float64
 13  payment_method      52 non-null     object
 14  shipping_status     47 non-null     object
 15  customer_rating     46 non-null     float64
 16  last_purchase_date  52 non-null     object
dtypes: float64(4), int64(1), object(12)
memory usage: 7.0+ KB

### Question 2: Missing Values Analysis
**Task:**
- Count missing values in each column
- Calculate the percentage of missing values
- Create a visualization showing missing data
- Identify columns with more than 10% missing values

In [43]:
# Your code here
df[df.isnull().any(axis=1)]
per=df.isnull().sum() /len(df)*100
per[per>10.0]

phone              13.461538
purchase_amount    17.307692
customer_rating    11.538462
dtype: float64

### Question 3: Duplicate Records Detection
**Task:**
- Find and display all duplicate rows
- Count how many duplicate records exist
- Identify which customer_ids have duplicates
- Display the duplicate records side by side

In [9]:
# Your code here

### Question 4: Data Type Issues
**Task:**
- Identify which columns have incorrect data types
- List columns that should be dates but aren't
- List columns that should be numeric but aren't
- List columns that should be categorical

In [10]:
# Your code here

### Question 5: Unique Values Analysis
**Task:**
- For each categorical column, display unique values and their counts
- Identify inconsistencies in categorical data (e.g., 'USA' vs 'usa', 'Male' vs 'M')
- List all unique values in gender, country, and payment_method columns

In [11]:
# Your code here

---
## Part 2: Handling Duplicates (Q6-8)
---

### Question 6: Remove Exact Duplicates
**Task:**
- Remove exact duplicate rows (keep first occurrence)
- Show how many rows were removed
- Verify no exact duplicates remain

In [12]:
# Your code here

### Question 7: Handle Customer ID Duplicates
**Task:**
- Find records with duplicate customer_ids but different data
- For duplicates, keep the record with the most recent last_purchase_date
- If dates are same, keep the record with higher purchase_amount
- Verify each customer_id is now unique

In [13]:
# Your code here

### Question 8: Duplicate Analysis Report
**Task:**
- Create a summary report of duplicate handling:
  - Total duplicates found
  - Duplicates removed
  - Final unique customer count

In [14]:
# Your code here

---
## Part 3: Data Type Conversion (Q9-12)
---

### Question 9: Convert Date Columns
**Task:**
- Convert 'registration_date' and 'last_purchase_date' to datetime format
- Handle multiple date formats (YYYY-MM-DD, MM/DD/YYYY, DD-MM-YYYY)
- Replace invalid dates ('n/a', 'UNKNOWN', 'N/A') with NaT
- Verify the conversion was successful

In [15]:
# Your code here

### Question 10: Convert Numeric Columns
**Task:**
- Convert 'age', 'purchase_amount', 'quantity', 'discount' to appropriate numeric types
- Handle text values like 'NULL', 'null', 'N/A' by converting to NaN
- Convert 'customer_rating' to float
- Show before and after data types

In [16]:
# Your code here

### Question 11: Standardize Text Columns
**Task:**
- Convert all text in 'customer_name' to title case
- Convert 'email' to lowercase
- Remove extra spaces from 'customer_name'
- Standardize 'gender' values (Male/Female only, convert M→Male, F→Female)

In [17]:
# Your code here

### Question 12: Standardize Categorical Values
**Task:**
- Standardize 'country' values (convert all variations to 'USA')
- Ensure 'payment_method' has consistent capitalization
- Convert 'gender' to categorical data type
- Show unique values after standardization

In [18]:
# Your code here

---
## Part 4: Handling Invalid Data (Q13-17)
---

### Question 13: Fix Invalid Age Values
**Task:**
- Identify age values that are invalid (< 18, > 100, or negative)
- Replace invalid ages with NaN
- Count how many invalid ages were found
- Display rows with invalid ages before fixing

In [19]:
# Your code here

### Question 14: Fix Invalid Purchase Amounts
**Task:**
- Find negative or zero purchase amounts
- Replace negative amounts with absolute value
- Replace zero amounts with NaN (assuming data entry error)
- Display affected records

In [20]:
# Your code here

### Question 15: Validate Email Addresses
**Task:**
- Create a function to check if email is valid (contains @ and .)
- Identify all invalid emails
- Replace invalid emails with NaN
- Count how many invalid emails were found

In [21]:
# Your code here

### Question 16: Validate Phone Numbers
**Task:**
- Check if phone numbers follow pattern: XXX-XXXX or similar
- Identify invalid phone numbers (like 'invalid-phone')
- Replace invalid phones with NaN
- Show examples of invalid phones found

In [22]:
# Your code here

### Question 17: Validate Ratings
**Task:**
- Ensure customer_rating is between 0 and 5
- Replace any ratings outside this range with NaN
- Display statistics of ratings before and after validation

In [23]:
# Your code here

---
## Part 5: Handling Missing Values (Q18-22)
---

### Question 18: Fill Missing Customer Names
**Task:**
- Identify rows with missing customer names
- Fill missing names with 'Unknown Customer'
- Verify no null names remain

In [24]:
# Your code here

### Question 19: Fill Missing Geographic Data
**Task:**
- Fill missing 'city' with 'Unknown City'
- Fill missing 'country' with 'USA' (most common)
- Show count of filled values

In [25]:
# Your code here

### Question 20: Fill Missing Numeric Data
**Task:**
- Fill missing 'age' with median age
- Fill missing 'purchase_amount' with median purchase amount by product_category
- Fill missing 'quantity' with median quantity
- Fill missing 'discount' with 0

In [26]:
# Your code here

### Question 21: Fill Missing Ratings
**Task:**
- Fill missing customer_rating with average rating by product_category
- If category average is not available, use overall average
- Round ratings to 1 decimal place

In [27]:
# Your code here

### Question 22: Handle Missing Shipping Status
**Task:**
- Fill missing shipping_status with 'Pending'
- Create a flag column 'status_was_missing' to track originally missing values
- Show count of filled values

In [28]:
# Your code here

---
## Part 6: Outlier Detection and Treatment (Q23-25)
---

### Question 23: Detect Purchase Amount Outliers
**Task:**
- Use IQR method to identify outliers in purchase_amount
- Create box plots to visualize outliers
- Display statistics of outliers
- Count how many outliers exist

In [29]:
# Your code here

### Question 24: Handle Age Outliers
**Task:**
- Identify age outliers using Z-score method (> 3 standard deviations)
- Display outlier records
- Cap outliers at reasonable limits (18-80)
- Show before and after distributions

In [30]:
# Your code here

### Question 25: Quantity Validation
**Task:**
- Identify unusually high quantities (> 15)
- Check if high quantities make sense with purchase amount
- Flag suspicious records
- Create a scatter plot of quantity vs purchase_amount

In [31]:
# Your code here

---
## Part 7: Data Consistency Checks (Q26-28)
---

### Question 26: Date Consistency Check
**Task:**
- Verify that last_purchase_date is after or equal to registration_date
- Find and display any records where this is violated
- Fix violations by swapping dates or setting to NaT
- Calculate customer lifetime (days between registration and last purchase)

In [32]:
# Your code here

### Question 27: Business Logic Validation
**Task:**
- Check if purchase_amount makes sense with quantity and product_category
- Verify that discount is not greater than 100%
- Ensure cancelled orders don't have 'Delivered' status
- Create a validation report

In [33]:
# Your code here

### Question 28: Cross-Column Validation
**Task:**
- If shipping_status is 'Delivered' or 'Cancelled', rating should exist
- Identify records violating this rule
- Fill missing ratings for completed transactions with category average

In [34]:
# Your code here

---
## Part 8: Final Cleaning and Export (Q29-30)
---

### Question 29: Create Comprehensive Cleaning Report
**Task:**
Create a detailed report showing:
- Original vs final dataset shape
- Number of duplicates removed
- Number of invalid values fixed per column
- Number of missing values filled
- Number of outliers handled
- Final data quality score (% of complete, valid data)

In [35]:
# Your code here

### Question 30: Export Clean Data
**Task:**
- Verify all data quality issues are resolved
- Ensure no null values remain in critical columns
- Export cleaned data to 'customer_sales_data_cleaned.csv'
- Create a data quality report file 'data_quality_report.txt'
- Display final dataset statistics

In [36]:
# Your code here

---
## Summary

### What You've Learned:
1. ✅ Data exploration and profiling
2. ✅ Duplicate detection and removal
3. ✅ Data type conversion
4. ✅ Invalid data identification and correction
5. ✅ Missing value handling strategies
6. ✅ Outlier detection and treatment
7. ✅ Data consistency validation
8. ✅ Comprehensive data cleaning pipeline

### Key Takeaways:
- Always explore data before cleaning
- Document all cleaning decisions
- Validate assumptions about data
- Handle edge cases carefully
- Create reproducible cleaning pipelines
- Maintain data quality reports

**Great job completing this comprehensive data cleaning practice! 🎉**